version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test-all:
    docker:
      - image: cimg/python:3.9 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - python/install-packages:
          - pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
  build-and-test-master:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout # check out the code in the project directory
      - python/install-packages:
          - pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
