version: 2.1

orbs:
  python: circleci/python@1.5.0
  docker: circleci/docker@1.7.0

jobs:
  build-and-test-all:
    docker:
      - image: cimg/python:3.9 # the primary container, where your job's commands are run
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
    steps:
      - checkout # check out the code in the project directory
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
  build-and-test-master:
    docker:
      - image: cimg/python:3.9
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
    steps:
      - checkout # check out the code in the project directory
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest

workflows:
  test:
    jobs:
      - build-and-test-all:
          context: mydockerhub
          filters:
            branches:
              ignore:
                - master
  test-build-deploy:
    jobs:
      - build-and-test-master:
          context: mydockerhub
          filters:
            branches:
              only:
                - master
      - docker/publish:
          context: mydockerhub
          filters:
            branches:
              only:
                - master
          docker-password: $DOCKER_PASSWORD
          docker-username: $DOCKER_USER
          image: $DOCKER_USER/lettings
          tag: $CIRCLE_SHA1,latest
          requires:
            - build-and-test-master