version: 2.1

orbs:
  python: circleci/python@1.5.0

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: oc-lettings-site
      GIT_HASH: $CIRCLE_SHA1
      APP_NAME: oc-lettings-1
    docker:
      - image: cimg/python:3.9

workflows:
  ci:
    jobs:
      - compile-and-test
      - docking:
          requires:
            - compile-and-test
          filters: # Build only on master branch
            branches:
              only: master
      - publish-on-dockerhub:
          requires:
            - docking
          filters: # Publish only on master branch
            branches:
              only: master

jobs:
  compile-and-test:
    executor: docker-publisher
    steps:
      - checkout
      - run:
          name: Create venv
          command: python -m venv venv
      - run:
          name: Activate venv
          command: source venv/bin/activate
      - run:
          name: Install reqs
          command: pip install -r requirements.txt
      - run:
          name: Run test PEP8
          command: flake8 --exclude 'env' 'migrations'
      - run:
          name: Run tests
          env:
            SECRET_KEY: $SECRET_KEY
            DNS_SENTRY: $DNS_SENTRY
          command: python manage.py test
  docking: #
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t $DOCKER_USER/$IMAGE_NAME:$CIRCLE_SHA1 .
      - run:
          name: Save docker image
          command: docker save -o image.tar $DOCKER_USER/$IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-on-dockerhub:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load saved docker image (image.tar)
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: push on dockerhub
          command: |
            docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
            docker push $DOCKER_USER/$IMAGE_NAME:$CIRCLE_SHA1
            docker logout